/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

/**
 *
 * @author Veronica Martínez
 */
public class Opciones extends javax.swing.JFrame {

    /**
     * Creates new form Opciones
     */
    public Opciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        opcProducto = new javax.swing.JMenuItem();
        opcCliente = new javax.swing.JMenuItem();
        opcPedido = new javax.swing.JMenuItem();
        opcAsesor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        opcSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo.jpg"))); // NOI18N

        jMenu1.setText("Archivo");

        opcProducto.setText("Producto");
        opcProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcProductoActionPerformed(evt);
            }
        });
        jMenu1.add(opcProducto);

        opcCliente.setText("Cliente");
        opcCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcClienteActionPerformed(evt);
            }
        });
        jMenu1.add(opcCliente);

        opcPedido.setText("Pedido");
        opcPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcPedidoActionPerformed(evt);
            }
        });
        jMenu1.add(opcPedido);

        opcAsesor.setText("Asesor");
        opcAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcAsesorActionPerformed(evt);
            }
        });
        jMenu1.add(opcAsesor);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Acciones");

        opcSalir.setText("Salir");
        opcSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcSalirActionPerformed(evt);
            }
        });
        jMenu2.add(opcSalir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void opcProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcProductoActionPerformed
        this.dispose();
        Producto prod = new Producto();
        prod.setVisible(true);
    }//GEN-LAST:event_opcProductoActionPerformed

    private void opcClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcClienteActionPerformed
        this.dispose();
        Cliente cliente = new Cliente();
        cliente.setVisible(true);
    }//GEN-LAST:event_opcClienteActionPerformed

    private void opcPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcPedidoActionPerformed
        this.dispose();
        Pedido ped = new Pedido();
        ped.setVisible(true);
    }//GEN-LAST:event_opcPedidoActionPerformed

    private void opcSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_opcSalirActionPerformed

    private void opcAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcAsesorActionPerformed
        this.dispose();
        Asesor ase = new Asesor();
        ase.setVisible(true);
    }//GEN-LAST:event_opcAsesorActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem opcAsesor;
    private javax.swing.JMenuItem opcCliente;
    private javax.swing.JMenuItem opcPedido;
    private javax.swing.JMenuItem opcProducto;
    private javax.swing.JMenuItem opcSalir;
    // End of variables declaration//GEN-END:variables
}
